### ISSUE TITLE
Looking forward to the 10-day and 30-day power consumption curve of CR2032.

### ISSUE THREAD

**Issue by zxl777** [rbaron/b-parasite#1]
Looking forward to the 10-day and 30-day power consumption curve of CR2032.
There is still a gap between theoretical estimates and actual conditions.

**Comment by rbaron** [comment]
Hi @zxl777,

I pulled all the real battery data I have here, which covers a period of a little less than 45 days. A few disclaimers:
* I use **5 minutes** intervals between broadcasts, so I would expect an upper limit of [~260 days](https://docs.google.com/spreadsheets/d/157JQiX20bGkTrlbvWbWRrs_WViL3MgVZffSCWRR7uAI/edit#gid=0) of runtime (instead of the estimated 480 days for 10 minutes intervals)
* The values I used for estimating the battery in the spreadsheet were empirically measured and rounded up
* I'm not super confident in the quality of the CR2032 batch I bought. I wouldn't be surprised if they pack less energy than advertised

Here's a screenshot of the data ([raw CSV data](https://github.com/rbaron/b-parasite/files/6454223/grafana_data_export.csv)):

![image](https://user-images.githubusercontent.com/1573409/117706460-9a4bc100-b1cd-11eb-8110-c8638505892a.png)

Over the period of a month, the battery voltage drops to around 2.65V. It's not super easy to estimate the battery discharging profile for our use case - 5-10 minutes of 3uA + 1-second pulse of 10mA. [This paper from Nordic](https://www.dmcinfo.com/Portals/0/Blog%20Files/High%20pulse%20drain%20impact%20on%20CR2032%20coin%20cell%20battery%20capacity.pdf) has some nice data for similar discharging patterns with deep sleep + pulse:

![image](https://user-images.githubusercontent.com/1573409/117709953-d3863000-b1d1-11eb-96df-c9867a6d5b82.png)

Chart D is the closest to our use case, and still has pretty high currents in comparison: 100uA sleep (vs. our 3uA) and 30mA 1-second pulses (vs. our 10mA 1-second pulses), but it gives us a nice baseline.

What I think is even nicer is that we can see in the chart D, `Vload` (the battery voltage during the active cycle, which is when we measure it) immediately drops to ~2.6V. This gives me a good feeling about the empirical data we're seeing in the dashboard/CSV I attached here, since we see that the battery voltage "quickly" (over ~30 days) drops to ~2.6V.

I'll keep an eye on this empirical data in the following months and document my findings here. Let me know what you think!
