### ISSUE TITLE
WiFi version

### ISSUE THREAD

**Issue by joedupa** [rbaron/b-parasite#27]
Hi, have you ever considered designing an ESP based version of the sensor for longer range and wider coverage of WiFi (comparing to BT) ? Thanks, and congrats on this project!!

**Comment by rbaron** [comment]
Hi @joedupa. Yes! Indeed that was my first design. You can still find it in [rbaron/w-parasite](https://github.com/rbaron/w-parasite). I found it's challenging to do do long running, low power stuff with ESP32 + WiFi. It pulls upwards of 250 mA when active (vs. ~10 mA with BLE) and using a LiPo + LDO means higher deep sleep current due to quiescent current (15 uA vs. ~3 uA for BLE). 

It might still be viable with chunkier batteries, but I find that for having many sensors deployed, smaller & more power efficient BLE sensors are a better choice for now.
