### ISSUE TITLE
Transmission Range

### ISSUE THREAD

**Issue by mjeanrichard** [rbaron/b-parasite#46]
HI,

Thanks for your Work. I created 10 of the version 1.2 bParasites and they work great. Except that the range is very limited. I can place my ESP32 (with ESPHome) no more that 10 meters (line of sight, no Walls) away from the bParasite before the connection drops.
Is anyone having similar Issues? Or is this the expected Range?

I think I already us the most powerfult Trasmission setting (PRST_BLE_ADV_TX_POWER 8).

Thanks for your help!

**Comment by rbaron** [comment]
Hi @mjeanrichard,

I'm glad to hear they're working (consider contributing to your community gallery #19!).

There are three params you can tweak in [prst_config.h](https://github.com/rbaron/b-parasite/blob/main/code/b-parasite/config/prst_config.h):
- `PRST_BLE_ADV_TX_POWER` (already set to max by default)
- `PRST_BLE_ADV_TIME_IN_MS` - the amount of time it spends advertising (repeating the same advertisement). Set to 1 second by default
- `PRST_BLE_ADV_INTERVAL_IN_MS` - the interval between two consecutive advertisement packets (30 ms by default)

These last two params are mostly optimized for power efficiency. I have increased both for a couple of my b-parasites and observed some extra range (at cost of shorter battery life), but I also opted for having two bridges instead of just one. 
Let us know if you manage to experiment with those params.

**Comment by mjeanrichard** [comment]
Ok, thanks for the suggestions. I will try to fiddle with the parameters.

What is the range you get out of yours?

**Comment by mjeanrichard** [comment]
My insights after a some testing and trials:
- Enabling Bluetooth 5 Long Range might help (no exact measurements yet)
- Some other optimizations in code might help as well
- Removing the Chip Antenna and soldering a wire with the appropriate length make a HUGE difference

I'll follow up with some measurement (power consumption and range).

**Comment by rbaron** [comment]
@mjeanrichard I've been meaning to experiment with Coded PHY for a while. I added a new flag [`PRST_BLE_EXPERIMENTAL_LONG_RANGE`](https://github.com/rbaron/b-parasite/blob/main/code/b-parasite/config/prst_config.h#L57) that will switch the advertising PHY to use Coded PHY.

I only had time to run a quick test:
- In one b-parasite, I set `PRST_BLE_EXPERIMENTAL_LONG_RANGE` to `1`
- On a different b-parasite, I hacked together a Coded PHY scan based on the [Coded PHY central from nRF Connect](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/samples/bluetooth/central_hr_coded/README.html#bluetooth-central-hr-coded)

It looks promising. Hopefully you can use this in the tests you're running.

I'm interested in if/how can we implement Coded PHY scanning in ESPHome. Right now I don't think it's possible, but they [do already support ESP32-C3/S3](https://esphome.io/components/esp32.html#esp-idf-framework), which I believe are Bluetooth 5 capable and can do Coded PHY.

**Comment by SystemFuchs** [comment]
Hi there,

due to the shortage for the chosen [E73-2G4M08S1C](https://www.ebyte.com/en/product-view-news.aspx?id=445) module I opted for the following version with an external ipex antenna socket (all other specs are identical) :

[E73-2G4M08S1CX](https://www.cdebyte.com/products/E73-2G4M08S1CX)

I've ordered the following [IBEX Antenna for 2.4G](https://www.amazon.de/gp/product/B07DC97PMY/ref=ppx_yo_dt_b_asin_title_o01_s00?ie=UTF8&psc=1) which can be easly put through the cover version with the hole. 

Assembled it a few minutes ago & the range seems to be massive improved. Got a signal from the 1st floor to the ESP32 in the basement. Placed two of the sensors in our glasshouse in the garden & signal reception is fine (ca. 15m from the glasshouse to the ESP32) :-) Btw have to water the tomato this evening :-D Thx a lot for this beautiful project & all the effort which was put into it. Still have to solder 13 E73 chips on the remaining boards but really love it!

![HomeAssistant](https://user-images.githubusercontent.com/3988026/185940333-d641aad9-a177-4e07-9620-e0d8a8b85c2e.png)
![Garden](https://user-images.githubusercontent.com/3988026/185942970-9b426836-8c8b-4a39-8e86-9f72429601a3.jpeg)
![Garden2](https://user-images.githubusercontent.com/3988026/185943074-9fe32aad-73e0-49b5-8bf0-8618bfc605c0.jpeg)

**Comment by rbaron** [comment]
That's awesome. Thanks for sharing @SystemFuchs.

**Comment by SystemFuchs** [comment]
> Cool, thanks for that input. For those who already have the module with the chip antenna, it can easily be desoldered and replaced with a piece of copper wire. I went with quarter wave and it works way better (even bent, see picture). Will do the same with the ESP32 to check if it improves further... ![IMG_20220822_201722](https://user-images.githubusercontent.com/778448/185991106-706331a7-8f80-4d49-9be0-1aab84d6571d.jpg)
> 
> @SystemFuchs Did you by any change measure the power consumption with this antenna? I would assume it stays the same, but would like some data...

Hi @mjeanrichard,

didn't do any measurements until now. How can I measure the power consumption of a parasite?

**Comment by Hedda** [comment]
> For those who already have the module with the chip antenna, it can easily be desoldered and replaced with a piece of copper wire.

Tip! With it using 2.4GHz you should normally make such monopole antenna length ~ 31.23mm long unless you know that the firmware is tuned for an antenna non-standard 2.4GHz length, and preferably use a 1mm diameter wire. 

Recommend search on Google for "Monopole Antenna Calculator" (and "Dipole Antenna Calculator" if prefer such an antenna design instead)

**Comment by RobertLukan** [comment]
I have replaced the ceramic antenna with monopole 31mm long wire(1mm diameter) and there is a significant improvement. I could notice about 20-25 dB improvement. I am not sure how to measure the power consumption, but I guess it should be the same as I have not changed anything else. Thanks for the tip.
