### ISSUE TITLE
Flashing b-parasite more than once using GDB

### ISSUE THREAD

**Issue by ZehelSitchel** [rbaron/b-parasite#71]
I flashed 4 b-parasite boards with the same firmware. Meaning that they all have the same MAC address. Realizing my mistake I edited the prst_config.h and changed the mac from f0:ca:f0:ca:01:01 to f0:ca:f0:ca:01:02, f0:ca:f0:ca:01:03, and f0:ca:f0:ca:01:04. Unfortunately GDB doesn't seem to pick up the board anymore. 

When the board is blank I ran the below to flash the boards.
> (gdb) monitor swdp_scan
> Target voltage: 3.3V
> Available Targets:
> No. Att Driver
>  1      Nordic nRF52 M4
>  2      Nordic nRF52 Access Port
> (gdb) attach 1
> Attaching to Remote target
> warning: No executable has been specified and target does not support
> determining executable automatically.  Try using the "file" command.
> 0x0001ae30 in ?? ()
> (gdb) load "bin/b-parasite_hex/s140_nrf52_7.2.0_softdevice.hex"
> Loading section .sec1, size 0xb00 lma 0x0
> Loading section .sec2, size 0xf000 lma 0x1000
> Loading section .sec3, size 0x10000 lma 0x10000
> Loading section .sec4, size 0x6634 lma 0x20000
> Start address 0x00000000, load size 155956
> Transfer rate: 27 KB/sec, 974 bytes/write.
> (gdb) load "bin/b-parasite_hex/nrf52833_xxaa.hex"
> Loading section .sec1, size 0x9000 lma 0x27000
> Loading section .sec2, size 0x52c lma 0x30000
> Start address 0x000272f8, load size 38188
> Transfer rate: 26 KB/sec, 954 bytes/write.

When trying to reflash the monitor swdp_scan just fails. Even after bridging the rst and gnd I can't get the boards to show up.
> (gdb) monitor swdp_scan
> Target voltage: 3.3V
> SW-DP scan failed!
> Failed

Anyone have a solution?
For reference I'm using a black magic probe v2.3b. b-parasite was compiled on WSL Ubuntu 22.04.1 LTS then flashed through GDB via Windows.

Edit: Added Ubuntu version

**Comment by drspangle** [comment]
I tried to reproduce the problem you had with my BluePill and couldn't. See if you can try the instructions I listed in #43 and maybe that will help?

**Comment by ZehelSitchel** [comment]
I'm going to rebuild my Ubuntu environment. I'll post my setup steps, it's certainly a good chance that I messed something up.

**Comment by rbaron** [comment]
@ZehelSitchel closing the issue for now. Please feel free to reopen.

**Comment by ZehelSitchel** [comment]
Well, it took me a LONG time to get back around to trying again. But I finally rebuilt my environment and was able to re-flash my b-parasites successfully.

With the code update I had to re-figure out how to compile and build it... but thankfully and sadly, with the help of ChatGPT, I was able to diagnose the errors and get it all working.

**Comment by rbaron** [comment]
@ZehelSitchel happy to hear it!

PS: Can we say we're AI-powered yet? 🥴

**Comment by Alcoinus** [comment]
@ZehelSitchel i am running into the same issue here. What exactly do you mean by "rebuilt my environment"?
Did you use a clean WSL install?

**Comment by ZehelSitchel** [comment]
@Alcoinus I am using a Ubuntu install on top of Windows Subsystem for Linux(wsl). So I just deleted the install, then restarted and rebuilt/reinstalled all the tools from scratch.

**Comment by Alcoinus** [comment]
I solved my issue and could successfully flash my b-parasites again (without a new black pill)🥳

For anyone running into the same issue:

The culprit was a changed pinout in the blackmagic firmware I was not aware about, which has been introduced with this commit: https://github.com/blackmagic-debug/blackmagic/commit/f9e63b47edbee4388d96d8943a1a238107bf4477
Unknowingly, I updated my black pill to the most recent blackmagic firmware before trying to flash my b-parasites again. 

As I wanted to keep using the JTAG pins on the black pill, I reverted the pinout for SWCLK and SWDIO to PA14 and PA13 respectively in https://github.com/blackmagic-debug/blackmagic/blob/main/src/platforms/common/blackpill-f4/blackpill-f4.h, compiled and flashed the firmware, and _swdp_scan_ was successful immediately after.
